### ISSUE TITLE
Your APC Plugin

### ISSUE THREAD

**Issue by rafaelmagic** [markjaquith/feedback#10]
Mark,

Any plans to update your APC Plugin to support APCu?

Thanks,

**Comment by markjaquith** [comment]
Do you have a specific reason to think it doesn't work?

**Comment by markjaquith** [comment]
I've been using this with PHP 5.5 and APCu and haven't had any problems. The API should be compatible — it's the same code, just given new life (and just the user cache portion). LMK if you find any issues.
