### ISSUE TITLE
How to serve Images from CDN (MaxCDN) without using any WordPress plugin

### ISSUE THREAD

**Issue by TanmayAhmed** [markjaquith/feedback#11]
I want to serve my site images from a subdomain hosted by MaxCDN. I don't want to install any caching plugin (W3TC or WP Super Cache).

**Comment by timnashcouk** [comment]
I know it's ask Mark anything and you have specified no plugin but have you tried https://github.com/markjaquith/WP-Stack
It has a CDN component that can be uploaded independently, so while technically a plugin is tiny.

I use it to do pretty much exactly what you describe,
If you want a step by step https://timnash.co.uk/building-cdn-ssl-cloudfront-certificates/ just jump to Set-up WP-Stack (to avoid the CloudFront bits as you are using maxCDN) but it really is a case of upload plugin, add two defines to wp-config.

**Comment by markjaquith** [comment]
@timnashcouk is right: you can use the WP Stack CDN drop-in. It just filters your output and points static resources to a CDN domain that you specify. I use MaxCDN myself, this way, and all users of Pressable hosting are using my drop-in.
