### ISSUE TITLE
Adding parameters to WordPress oEmbed

### ISSUE THREAD

**Issue by samikeijonen** [markjaquith/feedback#12]
I was trying to enable the JavaScript API for an embedded youtube-player. It means that I somehow needed to add &enablejsapi=1 to all youtube oEmbed url. When searching around I found a filter called `oembed_result`. Is this right hook or is there better way to do it?

This is how I got it working so far.

```
function my_plugin_enable_js_api( $html, $url, $args ) {

    /* Modify video parameters. */
    if ( strstr( $html,'youtube.com/embed/' ) ) {
        $html = str_replace( '?feature=oembed', '?feature=oembed&enablejsapi=1', $html );
    }

    return $html;
}
add_filter( 'oembed_result', 'my_plugin_enable_js_api', 10, 3 );
```

**Comment by markjaquith** [comment]
If you need to add that to the resulting HTML, then yeah, that seems reasonable!

**Comment by samikeijonen** [comment]
Thanks Mark.
