### ISSUE TITLE
WordPress in K12 Education

### ISSUE THREAD

**Issue by cswaim82** [markjaquith/feedback#15]
Hi Mark,

I am currently the Director of Information Technology for a small school district in Northern California.  We are looking to reach out into many new area's of Technology, Web Design being one of them.  We really starting looking into branching out during the success of the Hour of Code.  We would love to see if there is any information or instructional direction for K12 classroom's and lab's working with WordPress. I haven't found much information on fitting WordPress into instructional curriculum in school's but I am sure there is a ton of info out there.  I just haven't came across it.  Thanks for any info!

Chad

**Comment by MickeyKay** [comment]
Hi Chad, I'm not Mark, but I may have some info for you :)

We teach a basic WordPress class at our studio. Normally, we're teaching to adults and professional, but we have taught a mini-course catered to students as well. Bottom line: the kids loved it.

Let me know if you want to chat more. We have our own variety on a typical WordPress course curriculum too, and I'd be happy to share (pending bosses approval of course).

**Comment by markjaquith** [comment]
Education is not my strong point. You might want to reach out to @jenmylo, @andreamiddleton, or @lorelle to be pointed in the right direction!

**Comment by Lorelle** [comment]
There are some K12 programs out there with WordPress as an element, not usually as a core subject. I have the first college WordPress I (and II) course at Clark College in Vancouver, Washington, and it is now into its third year and a required fundamental in two degree programs and a cert, and an elective for other degree programs. You can contact me on Twitter at @lorelleonwp or through http://lorelle.wordpress.com/contact/ for more information. 

Thanks, and thanks, Mark.
