### ISSUE TITLE
Categorizing plugins

### ISSUE THREAD

**Issue by ghost** [markjaquith/feedback#2]
Mark, do you think it would be a good idea if...
1. WordPress categorized the plugin repository?
2. WordPress enabled users to categorized their 'favorites' list of plugins?

That is all,

Love Pete

**Comment by markjaquith** [comment]
We allow plugin authors to choose tags in their readme. What would be great for users is custom lists of plugins. Then on an install you could search for list:markjaquith/essential and install a bunch at once. Easy startup for a new site!
