### ISSUE TITLE
What hook is running if I call a function directly from a plugin/theme file?

### ISSUE THREAD

**Issue by MickeyKay** [markjaquith/feedback#22]
If, for example, I initialize a class directly in my plugin/theme file, without attaching it to a hook, where in the timeline of hooks is it firing? I tried to use `echo current_filter()` which returned nothing, so I'm thinking it must be before hooks have begun running maybe?

On a related note, I'm wondering the best method to ensure that a piece of my plugin runs before any other plugins. In this case, I'm working on a [Font Awesome library](https://github.com/MickeyKay/better-font-awesome-library) that I'd like to use to in multiple projects. The library relies on a singleton class with just the one instance. I have one plugin, [Better Font Awesome](https://wordpress.org/plugins/better-font-awesome/) dedicated specifically to creating some settings for this library, and I'd like to make sure it runs before any other plugin using the library, so that it's the one to create the initial instance with the appropriate settings. Thoughts?

Thanks Mark! I'll say it again and again: this forum rocks!

**Comment by jjeaton** [comment]
If you run a function right in your plugin file, it executes when the file is loaded, not on any hooks.

The `plugins_loaded` hook is a good one for running things as early as possible. That runs right after all the plugin files have been loaded. Are you trying to get something to load before the plugin file is loaded by PHP, or before a certain hook in the plugin is run?

You could also create a mu-plugin if something absolutely has to run before the plugins are even loaded.

**Comment by markjaquith** [comment]
Cosign on everything @jjeaton said.

For creating plugin interdependencies, I suggest that the "parent" plugin create its own hook that fires, say, late on `init`. Example:

``` php
<?php

// Define plugin class here

function get_my_parent_plugin_instance() {
    return MyParentPlugin::get_instance(); // defined in plugin as static, returns/creates instance
}

function my_parent_plugin_init() {
    do_action( 'my_parent_plugin_init', get_my_parent_plugin_instance() );
}

add_action( 'init', 'my_parent_plugin_init', 20 );
```

Then the dependent plugin just has to do:

``` php
<?php

function my_child_plugin_init( $parent_instance ) {
    $parent_instance->register_some_child_functionality( 'foo', 'bar' );
}

add_action( 'my_parent_plugin_init', 'my_child_plugin_init' );
```

Now you can safely activate the child plugin, and it will do nothing without the parent plugin active. It just registers its hook and waits for the parent plugin to become active and fire its init action, passing along a plugin class instance (not necessary, but I think it's a nice pattern).

If you don't control the child plugins, you'll have to see how they work. Do they defer their actions to `plugins_loaded` or `init` ? If so, just hook in on a lower priority. If they do stuff "live", meaning while the plugin file loads, then your options narrow. One option, as @jjeaton mentioned, it to use an `mu-plugins` drop-in. These run before regular plugins.

Another option, is to create an `mu-plugins` drop-in that filters `active_plugins` and bumps the parent plugin earlier in the plugin loading order, ensuring that its code runs first.

**Protip**: you can use this final suggestion to do all sorts of useful things, like make plugins that are always active, or only active in some circumstances. For instance, make Debug Bar always active in dev environments, but never in production. I've used this to make sure WooCommerce (a hefty plugin) doesn't run at all on pages I know don't need it, to get that extra little bit of speed.
