### ISSUE TITLE
Page links to and lightbox

### ISSUE THREAD

**Issue by sohels** [markjaquith/feedback#25]
Hi Mark,

Here's the site I'm building: http://southblock.in/

To redirect users to the original source for news articles, I'm using your page-links-to plugin (https://wordpress.org/plugins/page-links-to/).

What I'd like to do is open the url in a lightbox (or other pop-up) on the same page, rather than in a new tab or new page. I've tested this out here: http://southblock.in/demo/

But I can't seem to do this on the main page (http://southblock.in/) even if I use the exact same href structure - was wondering if there's some conflict with page-links-to?

Ideally I'd like to modify the plugin such that there's a second check-box in the page-links-to UI so that I can easily choose to open the link in a new tab or lightbox.
![screenshot 1](https://cloud.githubusercontent.com/assets/7658459/3041130/dffa19ae-e0f1-11e3-8d30-52ebb5a47cb8.png)

Can you please guide me on how I can do this? Thanks in anticipation!

-Sohel

**Comment by markjaquith** [comment]
Most lightbox plugins need some way of designating links to open in a lightbox. Like a class on the link, or something. Page Links To doesn't currently have the ability to add/alter classes. What you might be able to do is have your lightbox code "read" the `pltNewTabURLs` JavaScript variable (which is an array of URLs that should be opened in new tabs), and apply the special lightbox class to all links that match those URLs. This is precisely how PLT marks those links as opening in new tabs. Look at your page's source for code starting with: `<script>var pltNewTabURLs =`.
