### ISSUE TITLE
Documenting PHP - how much detail?

### ISSUE THREAD

**Issue by MickeyKay** [markjaquith/feedback#26]
The suggested WordPress PHP documentation standards (http://make.wordpress.org/core/handbook/inline-documentation-standards/php-documentation-standards/), based on PHPDoc, contain a LOT of suggestions and details. Yet a lot of the code I've come across, including parts WP Core, seems to take a much less detailed approach - omitting various @ tags, not following the guidelines on period usage at the end of certain descriptions but not others, providing comment blocks for class constants, etc.

How precisely do you think these guidelines need to be followed? Balancing the importance of thorough documentation with the desire to just get things done (without having to comment every variable you create), where do you fall on the spectrum? Anything you think is particularly important/unimportant?

Thanks!

**Comment by markjaquith** [comment]
This might be a better question for @DrewaPicture and the WordPress core inline documentation team. Drew?

**Comment by JDGrimes** [comment]
Also keep in mind that much of the documentation in WP core may be kind of old. Minor improvements to bring it inline with the current guidelines are usually not considered good patches. As with the code styling changes, these fixes are generally put off until they can be a part of more substantial changes. I think the guidelines are intended to be followed moving forward, but it will be many years before core actually reflects those guidelines.

**Comment by markjaquith** [comment]
As for me personally, I tend not to include a lot. What it accepts and what it returns are the most important.

**Comment by DrewAPicture** [comment]
Sorry fellas, I forgot all about responding here. Yes, the standards should be followed going forward, as for going backward, I'm working on it as fast as I can :)
