### ISSUE TITLE
Best Practices - Themes & Options

### ISSUE THREAD

**Issue by thatryan** [markjaquith/feedback#27]
Hey Mark, thanks for this opportunity and offer of help!

I am planning a full overhaul of 15 custom themes I built on our MultiSite network and have a couple questions regarding the best way to accomplish a few things.
1. As far as "best practice" standards for template development, is the underscores, https://github.com/automattic/_s template an up-to-date and good way to start? Is there a better theme to study?
2. The layouts I am building are going to rely heavily on customizing ability for colors and fonts by the users as that is what they all want. So regarding custom theme options, is it considered bad practice to use a framework such as Redux Framework, http://reduxframework.com/ ? 

Thank you!

**Comment by markjaquith** [comment]
I haven't used Underscores in a year or two, but at the time, it was a perfectly good starting point for a theme.

I don't have familiarity with Redux. Best practice would be to integrate with the theme customizer, so they have live feedback of their color changes!
