### ISSUE TITLE
On clicking publish in a post, what does Wordpress do?

### ISSUE THREAD

**Issue by murrayac** [markjaquith/feedback#29]
So I've published thousands of posts, with images, terms, taxonomies and so on, and all this takes is creating a new post then clicking publish. I was wondering what Wordpress does behind the scenes.. is it very complex? For example- what actions, hooks and order WP writes to tables.

**Comment by bueltge** [comment]
I analyze this with the plugin [Debug Objects](https://github.com/bueltge/Debug-Objects), this list the hooks, there was fired. This is not an 100% secure image of process, but helpful.

**Comment by murrayac** [comment]
Thanks Bueltge, I'll take a look and watch the power behind the beauty.

**Comment by markjaquith** [comment]
Quite a lot happens! You should start with `edit_post()` in `wp-admin/includes/post.php`... and follow that through. The lowest level functions we have are `wp_update_post()` and `wp_insert_post()`, so if you're looking for how it works without the "normal publish flow" adornments, start there.
