### ISSUE TITLE
Versioning, releasing, sharing on Github

### ISSUE THREAD

**Issue by MickeyKay** [markjaquith/feedback#30]
What are your thoughts on best practices for releasing projects/code via Github?

I ask because we recently ran into an issue that has me a bit puzzled in terms of best practices. We have a Genesis child theme that we host via Github and recently discovered there was a bug that needed fixing. We patched the bug, tested, committed the update, and even added a big note at the top of the README.md file to let users know about the bug's existence prior to the specific commit we had just made, but there are still however many users out there who have no idea this bug exists. I'm sure in some cases, for certain projects, uses are pulling in the most current version pretty continuously (which would mitigate this problem), but that's not the case for our child theme, since most users are probably just downloading it to desktop and adding to their WP install. That's the issue in a nutshell. . .

So my questions are:
- Any general suggestions on how best to share things via Github _and_ ensure that users will update when necessary?
- Is it just better to use something like EDD with the Versions add-on so users get notifications when an update is available?
- Are there other common best practices when releasing/sharing code like this to guarantee all users at least know about available updates?

Thanks Mark!

**Comment by MickeyKay** [comment]
. . . and I just found the Github Updater plugin:
https://github.com/afragen/github-updater

That's probably a good place to start. Still open for other tips.

**Comment by markjaquith** [comment]
I've honestly only used EDD for private code. But you could probably use that code (or look at the code in core Genesis) and use a GitHub hosted static file as the endpoint, which returns information about the latest version (like where to download the zip). The GitHub updater plugin looks like just what you want, however!
