### ISSUE TITLE
Mixing Object Oriented Programming & Functional Programming

### ISSUE THREAD

**Issue by MickeyKay** [markjaquith/feedback#32]
What are your thoughts on best practices for mixing OOP and functional programming in projects? As a newcomer to OOP still trying to learn best practices, I was operating under the impression that if I'm going to create an OOP, pretty much every bit of functionality should exist within an object.

Lately, however, I've come across various plugins that mix a foundation built on classes with various files that contain functions outside of any object scope. Can you speak to reasons for mixing like this, instead of just enclosing the functions within a utility class or something of the sort? Any insights? Thanks!

**Comment by markjaquith** [comment]
I would generally just enclose things inside an object, just for encapsulation, reduction of global symbols, and shorter method names. `$this->get()` reads better than `my_awesome_plugin_get()`.
