### ISSUE TITLE
MultiSite and Theme Options

### ISSUE THREAD

**Issue by thatryan** [markjaquith/feedback#34]
Two parts here :)

Preface:  I create a master parent theme to run all the "main" code for the sites on our network, and each site has its own child theme for styling and tweaks. Each site shares common options and settings that would be modified.
1. If I add the settings I need via Theme Customizer in the parent theme, will each sub site be able to use the settings themselves? Is that data store separate for each sub site even though sharing a parent theme?
2. The two ways to store data, either theme_mod or option, am I correct that option should be used for settings that would need to persist if the theme changed, and theme_mod for settings that are theme (or, child theme) specific?

Thanks Mark!

**Comment by momekh** [comment]
Why, may I ask, was this beautiful question marked _closed_ by the questioner!? 

+1 \* infinity please.
