### ISSUE TITLE
HHVM + Batcache

### ISSUE THREAD

**Issue by mauryaratan** [markjaquith/feedback#37]
Hey Mark!

I was wondering if you have any guides available somewhere to get HHVM and Batcache running? Been struggling for a while now but I always end up with an issue.

Any help would be highly appreciated :smile:

**Comment by markjaquith** [comment]
I haven't had any specific issues. HHVM supports APC user cache and Memcache, so if you drop in the object caching backend for one of those (and for Memcache, configure it and have it running), Batcache should just work.
