### ISSUE TITLE
How to thoroughly test wp_remote_get() return

### ISSUE THREAD

**Issue by MickeyKay** [markjaquith/feedback#39]
Hi there,

I've been using `wp_remote_get()` in a recent project and have been trying to refine the process by which I process the returned response. Specifically, I'd like to know the best way to check the call was successful _and_ returned some valid content. I've seen various test conditionals, however none of them seem to fully work. Amongst several possible return values I need to test for are:
- A successful get request that returns actual remote data.
- A WP_ERROR - what happens if the URL isn't valid, or the server is down, or any number of things.
- A 404 error - for whatever reason, this doesn't return a WP_ERROR and therefor needs it's own test.
- Others?

I would love to see a comprehensive set of conditionals that checks to make sure the remote fetch connected _and_ returned valid, useful data. Any ideas? Thanks!

**Comment by afragen** [comment]
Hey Mickey,

While certainly not exhaustive, I use the following in some code, https://github.com/afragen/github-updater/blob/develop/includes/class-github-api.php#L88L100

**Comment by markjaquith** [comment]
First, check against `WP_Error`. Next, check the data returned. Or use the response code to indicate various error situations.
