### ISSUE TITLE
Installing WordPress submodule

### ISSUE THREAD

**Issue by isaacalves** [markjaquith/feedback#44]
Hey Mark, this is probably a ridiculous question but I can't find an answer. 

How do you install the WordPress submodule to your repo? Should I install inside the `wp` empty folder?

I tried `git submodule add git://github.com/WordPress/WordPress.git wp`, but it throws me the message: 

"'wp' already exists in the index"

Thank you

**Comment by swissspidy** [comment]
The submodule is already added, that's why you get this message. To install and update WordPress, use something like `git submodule update --recursive`.

**Comment by markjaquith** [comment]
:+1:  to @swissspidy's answer.
