### ISSUE TITLE
Which redis object cache dropin?

### ISSUE THREAD

**Issue by pjv** [markjaquith/feedback#49]
After emailing you directly to ask this yesterday, I just saw this github/AMA thing. Great idea.

My question is: would you mind telling me which specific redis object cache dropin you are using successfully with HHVM? i have tried two of them - one didn’t work for me at all and with the other, HHVM started eating CPU at 4X normal and performance was, if anything, degraded.

**Comment by markjaquith** [comment]
Hmm. I don't know that I've used HHVM + Redis. But the backend I've used on PHP-FPM successfully is this one:

https://wordpress.org/plugins/wp-redis/
