### ISSUE TITLE
How do you feel about ISIS using WordPress?

### ISSUE THREAD

**Issue by nastyhobbits** [markjaquith/feedback#52]
Why are you hosting the Jihaadist 'Inspire' magazine? It contains detailed information about building car bombs and tips for selecting targets to inflict maximum civilian casualties. Your company may be inadvertently contributing to the deaths of thousands of people.

**Comment by markjaquith** [comment]
WordPress isn't a company, and it doesn't host any sites. It’s just software that you can download and host somewhere else. We have no control over where people install it, or what content they put on the sites they build with it. No legal control, and no actual control. Jihadis could also be making paper fliers in Microsoft Word, but that wouldn't make Microsoft responsible for the content of those fliers.
