### ISSUE TITLE
From Zero to.... Mark!

### ISSUE THREAD

**Issue by redrambles** [markjaquith/feedback#54]
You are living in a parallel universe where you haven't touched WordPress at all. You decide to get started, and somehow - suddenly - you tap into some higher power that guides you towards the most efficient, dead-end and pothole-free pathways from novice to WordPress God. 

Inexplicably, you feel compelled to sketch out such a path for the rest of us. 

:)

**Comment by markjaquith** [comment]
1. Read the source. Our inline documentation is rapidly becoming great, but there are nuances, and sometimes a deep code dive is the best way to see how things really work.
2. Go to WordCamps and make contacts with developers you respect.
3. Inspect the code written by those people. See how they're accomplishing things.
4. Ask respected dev how they develop. What tools and processes they use.
5. Write WordPress code with `WP_DEBUG` turned on.
6. Follow WordPress core development, to see where core is headed and to be both ready for changes and in a position to raise objections if you think something is going to cause problems for your existing code.

**Comment by redrambles** [comment]
Thank you!
