### ISSUE TITLE
WP site due diligence eval

### ISSUE THREAD

**Issue by fhaubensak** [markjaquith/feedback#55]
Hi Mark -

I'm interested to find someone that can look at some code in preparation for our site to get put through the ringer from investors technical due diligence. Our wp site is heavily custom coded, and with the team in India, we want to be able to say: 1. We can scale the site, 2. Its more or less robust, 3. we can defend how things were done, etc.

I'm interested to find the right person to help do this, thinking you'd be interested or know others who may.

Thanks!
Fred Haubensak
Operations Director, Skillsapien
650-248-4619

**Comment by markjaquith** [comment]
Hey Fred,

Yeah, this is something I can do, although I'm not available for new work until April.
