### ISSUE TITLE
WordPress question..

### ISSUE THREAD

**Issue by PaulCoughlin** [markjaquith/feedback#58]
Hi Mark,

With WordPress, I think one of the biggest pains, is when moving or deploying sites, and having to change references to the domain the existing site is on/site url. Seems a search/replace on the database is how it's handled usually..

But if WordPress has an actual value, stored in its database - like the site url, then why not use that value as a variable in everything internally? 

Wouldn't it be good to have every reference to the site url stored internally as a simple variable, so that only 1 value has to be changed when deploying or moving sites?

I get I'm oversimplifying, but the idea seems a good one to me :-)

Thanks,
Paul

**Comment by markjaquith** [comment]
You should really only see URLs hardcoded in post content. We are very cautious about modifying people's post content. Take something like: `<a href="http://example.com/some-link/">internal link</a>`. Yeah, we could change that to `<a href="/some-link/">internal link</a>`, but what if you wanted to export that content to a different site? Then the link would break. What if you wanted to move some content to another site, and then move the first site to a new domain? If the URLs are left as absolute in the content, it’s clear where they should point, no matter where the content ends up.

WP-CLI has a command to do search and replace, and doing a search/replace on `post_content` is pretty trivial.

http://wp-cli.org/commands/search-replace/

**Comment by PaulCoughlin** [comment]
Thanks Mark - much appreciated..  Paul

------ Original Message ------
