### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by ceuley** [markjaquith/feedback#59]
Hey Mark,

Question regarding your plugin "Disable Canonical URL Redirection"
I am using it and it seems to work fine, but one part of it is interfering with my FONT AWESOME icons.

See: http://www.mysa-store.org (this is the redirect HTML Static page)
WP: http://www.mysa-store.org/index.php (this is were the issues are, my SEARCH, SOCIAL MEDIA icons are non-visible) I was told by the theme author that it had to do with the redirect / header code interruptions from the plugin.

Can you assist?

**Comment by ceuley** [comment]
oh, so if you visit the site without the WWW (http://mysa-store.org/index.php) then the icons show up.

**Comment by markjaquith** [comment]
They seem to be showing up for me on both versions of the domain name.
