### ISSUE TITLE
Register Issues

### ISSUE THREAD

**Issue by BigDDDD** [markjaquith/feedback#6]
Hi Mark.  Very kind of you to make such an easy forum for us to use.  Thank You for your time.

I am not a prolific code writer.  Just a 60-year-old who knows more than most 60-yr-olds.  I am trying to develop this site on Bluehost usuing WordPress and require that it be held unviewable to the general public.  I want users to register  and then have me "approve" their membership before entering the webiste.

I've chosen a few Plug-ins (Private Community for BP Life, WP Login Box, Confirm User Registration, and BuddyPress Pending Activations) which gives me what I am looking for.  Except for one bug.  New users, while finishing their Registration, get a meesage that implies that "Now you are in" when, in fact, they have to wait for me to approve/activate them.  How would I change this message to let them know about the approval process and await their true approval?  Thanks again for your time.

**Comment by afragen** [comment]
Try using the New User Approve plugin, https://wordpress.org/plugins/new-user-approve/
It works great for me.

**Comment by markjaquith** [comment]
I don't actually know a lot about these plugins. But I would look at @afragen's suggestion. If that fails, look for the exact sentence that the user sees, and then search the code locally on your computer to see what is generating that. There might be a filter or an option you can use to customize it.

**Comment by BigDDDD** [comment]
Thank Yopu afragen and Mark.  I've already tried the plugin that you suggest but, lo and behold, my email has stopped working with bluehost.  It seems that THEY have labeled me a spammer (which I am not) and it will take a few days for them to fix.  So, I won't know if this solution works for me until later in the week.
