### ISSUE TITLE
WP multisite development staging

### ISSUE THREAD

**Issue by mattada** [markjaquith/feedback#62]
We dont do a lot of WP multisite projects, but have a bigger one coming up. 

What are your suggestions on a development environment for testing, staging and later deploying a wp multisite using the subdomain url hierarchy? Right now the current genius idea is to just buy a new URL. Somesite-beta.com style. I feel thats not the right answer. 

thanks!

**Comment by markjaquith** [comment]
Why not double subdomain it? `subsite.beta.domain.com` and `anothersite.beta.domain.com`
