### ISSUE TITLE
What are you think about cloudflare?

### ISSUE THREAD

**Issue by mustafauysal** [markjaquith/feedback#63]
As a consultant, probably some of your clients using it. So I wondered what are you think about cloudflare with WordPress?

**Comment by markjaquith** [comment]
I like it in theory. I've experienced issues where their 30 second max execution timeout has caused problems. And when Cloudflare goes down, that sucks.

Also you need to do some extra work to get Clourdflare to cache HTML pages. But it’s definitely worth it, because it makes you really scalable.
