### ISSUE TITLE
Wordpress permission issues on Ubuntu

### ISSUE THREAD

**Issue by TechMonkey01** [markjaquith/feedback#64]
So we are hosting a few wordpress sites on an Ubuntu Server and having trouble getting the file permissions to let the Wordpress install write files directly to the file system (i.e. Plugin Updates) without setting everything to 777.  Local to FL and would love to see about getting your expertise in setting up the whole server for best practices with WP.

**Comment by TechMonkey01** [comment]
Tampa region...

**Comment by markjaquith** [comment]
The files should be owned by the process that runs the web server, and be writable for that user.
