### ISSUE TITLE
Lost admin WP site permission??

### ISSUE THREAD

**Issue by billglewis** [markjaquith/feedback#65]
Hi Mark,

Any thoughts on getting back an admin setting? I have BU of DB and site. I have seen the site (Jet Pack report) go down the last few days 8-10 min at a time. Did not think to much about it but today I login with my admin and I am only at best an editor it would seem.  Any thoughts on getting back to admin status?
I may have been hacked?

Thanks!

Bill

**Comment by markjaquith** [comment]
If your role got changed, you could manually change that in the database. Look at the usermeta rows for your user ID, and you should spot it. Note that serialized values indicate their length, so `editor` is 6, while `admin` is 5.

Honestly this should be more intuitive.At the very least, blanking the user roles option should force it to be repopulated to default values.
