### ISSUE TITLE
The road less traveled

### ISSUE THREAD

**Issue by thinkhuman** [markjaquith/feedback#67]
Mark, if you were 18 again, what would you do with your life, professionally speaking?

**Comment by markjaquith** [comment]
I would spend more time learning programming languages and getting involved in open source projects, where your skills are fire-tested against sometimes harsh expectations. My main regret is not finding my calling sooner. It took me until 2005 to really recognize that this web publishing software thing wasn't just a hobby, it was a calling and a career.
