### ISSUE TITLE
Caching, load balancers, and shared file systems

### ISSUE THREAD

**Issue by MickeyKay** [markjaquith/feedback#68]
Hi Mark,

Question for you. . .

What would your ideal caching/optimization setup be for a site that runs super-high traffic across a load balancer. Added to the mix, part of the file system is shared, however some is distributed across several servers. It sounds like a lot of the go-to caching setups don't necessarily work when utilizing a load balancer setup - several articles I've come across have said that memcached is the only way to go in this type of setup, as other caching methods won't work very well. That said, I haven't come across much info on why certain setups will/won't work.

So, I would love to hear your thoughts on what your ideal caching/optimization stack might look like for the above described setup. In our case, we're hosted with AWS using a load balancer, Gluster for the shared file system, and Cloudflare as a CDN for our assets. 

Any input would be great - thanks!

**Comment by markjaquith** [comment]
Redis or Memcache for object caching. I would never use filesystem-based caching on a network-based filesystem like NFS. You'll hit throughput issues, and lag, and it’s just a mess.
