### ISSUE TITLE
Merging local with live

### ISSUE THREAD

**Issue by rob-teamworks** [markjaquith/feedback#69]
One thing that's caused us huge problems is merging changes from local to live - where local data and files are merged with the live version... without copying over or losing data.

So in the real world, a client asks for a new feature but continues to use the site (adding new posts etc). At the same time we are adding new features and posts on the local version. So we've got two versions of the database that need merging.

The closest thing we've found is https://wpstagecoach.com/. It creates a staging site from the live version where you can ftp into it and make new features. It then allows you to merge back with the live site so new features are added to the live data... rather than just copying over it.

The problem with this is that it doesn't allow us to work locally and therefore go through our other processes. Also, what if the stagecoach servers go down... we then have no way to work on the website.

Mark, how do you handle this situation? What do you do to merge local to live without losing data?

Here's our current process, as you can see we can't get the left side working with the right side of the diagram (there's probably other holes too but this is the biggest one!).

![download-1](https://cloud.githubusercontent.com/assets/898082/12447649/2bfa1f6e-bf69-11e5-9bc3-4423890f6a29.png)

**Comment by markjaquith** [comment]
I am actively working on a project that will solve this **exact** issue, and allow you to work locally (or on a staging server that you control), record data changes, and play them back on production (either immediately, from a queue, or via an `mu-plugins` "script" that runs in conjunction with file changes you've made (like adding a new plugin, which then gets configured by the script). My plan is to release it by the end of the year.
