### ISSUE TITLE
Best ways to speed up a WordPress + WooCommerce install?

### ISSUE THREAD

**Issue by markdeldegan** [markjaquith/feedback#7]
I'm having some site loading issues with a WordPress/WooCommerce store. I realize that for the best user experience page speed is vitally important.

What would be some of the best ways to speed up a site like this?

**Comment by markjaquith** [comment]
Is WooCommerce functionality present on every front end page? If not, you might consider not running it on those pages (you can dynamically alter the list of loaded plugins on the fly, say in response to a URL pattern).

If you can avoid doing dynamic page views for everyone shopping in your store, you should do that. Obviously the shopping cart and checkout pages have to be dynamic, but consider the dynamic-ness of your store listing pages.

Insert timing functions at various places in your templates to see what things are the most expensive. Consider doing output fragment caching for these bits. Like, you might have a footer that shows popular products. You don't need this to be run live on every load. Cache it and only "do it live" once a day.
