### ISSUE TITLE
Applying Wordpress Membership Management to another Web Site

### ISSUE THREAD

**Issue by bwqr** [markjaquith/feedback#73]
My big issue is about to make a web site that people can attemp to sing up or log in and I want to it in a good way. While I was searching the how to do it, I saw the wordpress and I liked its management. So, is there any way to copy wordpress membership managemnt to may site. Thanks a lot for your help.

**Comment by markjaquith** [comment]
You could just move your non-WordPress site into WordPress using the Pages feature, and protect it using the WordPress membership plugin of your choice.
