### ISSUE TITLE
Which development kits?

### ISSUE THREAD

**Issue by mustafauysal** [markjaquith/feedback#8]
I'm just wondering which ide/editor are you using for development? (netbeans,phpstorm, sublime,atom... )

**Comment by markjaquith** [comment]
I use Sublime Text 2 for most of my development. I have played with Atom, but it's very young, and not ready for my daily use. I'll sometimes fire up TextMate for quick jobs. And for large files or on-server editing, I'll use Vim.

I haven't found an IDE that I really like enough to use daily.
